.Dd January 1, 1970
.Dt forge tech
.Os Runxi Yu
.Sh NAME
.Nm forge
.Nd Fore Workflows
.Sh DESCRIPTION
.Pp
I generally use
.Lk https://git.runxiyu.org/ my own Git server
for my projects. I also use my
.Lk https://sr.ht/~runxiyu sr.ht account
for
.Lk https://todo.sr.ht/~runxiyu issue tracking
and
.Lk https://lists.sr.ht/~runxiyu mailing lists,
and
.Lk https://git.sr.ht/~runxiyu their Git
for some projects too.
.Pp
Regardless of whether I'm using my own infrastructure with plain Cgit
and plain mailing lists (except that my mailing list manager is slightly
broken for now), or the slightly better-integrated environment sourcehut
provides, a contributor who wishes to submit some of their commits may
simply do the following with
.Lk https://git-send-email.io git-send-email
.Bl -enum
.It
Configure git-send-email (only once!)
.It
Clone the repository to a local directory
.It
Make some changes and commit
.It
.Ql git send-email HEAD^ --to='~runxiyu/public-inbox@lists.sr.ht'
or something similar
.El
.Pp
This is much easier, imo, than the pull-request workflow popularized by
GitHub (which is proprietary by the way) and similar forges:
.Bl -enum
.It
Register an account on the forge (once per forge)
.It
Click “fork” on the repo's Web interface
.It
Clone the fork to a local directory
.It
Make some changes and commit
.It
Push
.It
Go back to the Web interface to create a PR (which often involves
clicking at least three buttons)
.It
Delete your redundant fork once the PR is merged and your repo is
not really useful anymore
.El
.Pp
Why do certain people hate on SourceHut?
